source/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_market.urls'))
]

source/my_market/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from my_market.views.base import index_view
from my_market.views.add_view import add_product_view
from my_market.views.detail_view_product import detail_view_product
from my_market.views.view_categories import add_category_product,  view_categories

urlpatterns = [
    path('', index_view, name='home'),
    path('add/product/', add_product_view, name='add_product'),
    path('add/category/', add_category_product, name='add_category'),
    path('view/product/<int:pk>', detail_view_product, name='detail_view_product'),
    path('view/categories/', view_categories, name='view_categories'),
    # path('edit/category/<int:pk>', edit_category, name='edit_category')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

source/my_market/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length=50, db_index=True, unique=True, verbose_name='Категория')
    description = models.CharField(max_length=200, blank=True, null=True, verbose_name='Описание')

    def __str__(self):
        return f'{self.category_name}'


class Product(models.Model):
    product_name = models.CharField(max_length=50, verbose_name='Продукт')
    description = models.TextField(max_length=2000, blank=True, null=True, verbose_name='Описание')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='category')
    add_date_time = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')
    price = models.DecimalField(max_digits=11, decimal_places=2, verbose_name='Стоимость')
    image = models.ImageField(upload_to='product/%Y/%m/%d', default='default/placeholder.png',  verbose_name='Картинка')

    def __str__(self):
        return f'{self.product_name} \n {self.price}'

source/my_market/forms.py
from django import forms
from my_market.models import Product, Category


class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('product_name', 'description', 'price', 'category', 'image')


class AddProductCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('category_name', 'description')

source/my_market/views/add_category_product.py
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import render, redirect
from my_market.forms import AddProductCategoryForm

source/my_market/views/add_view.py
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import render, redirect
from my_market.forms import AddProductForm


def add_product_view(request: WSGIRequest):
    if request.method == 'GET':
        form = AddProductForm()
        return render(request, 'add_product.html', context={'form': form})
    else:
        form = AddProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home')

source/my_market/views/base.py
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import render

from my_market.models import Product


def index_view(request: WSGIRequest):
    products = Product.objects.all()
    return render(request, 'index.html', context={'products': products})

source/my_market/views/detail_view_product.py
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import render, get_object_or_404

from my_market.models import Product


def detail_view_product(request: WSGIRequest, pk):
    product = get_object_or_404(Product, pk=pk)
    return render(request, 'detail_view_product.html', context={'product': product})

source/my_market/views/view_categories.py
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import render, get_object_or_404, redirect

from my_market.forms import AddProductCategoryForm
from my_market.models import Category


def add_category_product(request: WSGIRequest):
    if request.method == 'POST':
        form = AddProductCategoryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = AddProductCategoryForm()
        return render(request, 'add_product_category.html', context={'form': form})


def view_categories(request: WSGIRequest):
    categories = Category.objects.all()
    return render(request, 'categories_view.html', context={'categories': categories})


def category_view(request: WSGIRequest, pk):
    category = get_object_or_404(Category, pk=pk)
    return render(request, 'detail_view_category.html', context={'category': category})


# def edit_category(request: WSGIRequest, pk):
#     if request.method == 'GET':
#         category = get_object_or_404(Category, pk=pk)
#         return render(request, 'edit_category.html', context={'category': category})



    

source/my_market/templates/add_product.html
{% extends 'base.html' %}
{% block title %}Add Product{% endblock title %}
{% block content %}
<div id="content-main">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="submit" value="Add product">
    </form>
</div>
{% endblock content %}

source/my_market/templates/add_product_category.html
{% extends 'base.html' %}
{% block title %}Add Category{% endblock title %}
{% block content %}
<div id="content-main">
    <form action="" method="POST">
        {% csrf_token %}
        {% if field.errors %}
            <div class="alert-danger">{{ field.errors }}</div>
        {% endif %}

        <table>
            {{ form }}
        </table>
        <input type="submit" value="Add category">
    </form>
</div>
{% endblock content %}

source/my_market/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/dark_mode.css' %}">
    <link rel="stylesheet" href="{% static 'css/nav_sidebar.css' %}">
    <script src="{% static 'js/nav_sidebar.js' %}" defer></script>
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
    <script src="{% static 'js/vendor/jquery/jquery.js' %}"></script>
    <script src="{% static 'js/jquery.init.js' %}"></script>
    <script src="{% static 'js/core.js' %}"></script>
    <script src="{% static 'js/admin/RelatedObjectLookups.js' %}"></script>
    <script src="{% static 'js/actions.js' %}"></script>
    <script src="{% static 'js/urlify.js' %}"></script>
    <script src="{% static 'js/prepopulate.js' %}"></script>
    <script src="{% static 'js/vendor/xregexp/xregexp.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

<div id="header">
    <div id="branding">
        <h1 id="site-name"><a href="{% url 'home' %}">My Market</a></h1>
    </div>
    <div id="user-tools">
        <a href="{% url 'home' %}">Products</a> |
        <a href="{% url 'view_categories' %}">Categories</a> |
        <a href="{% url 'add_product' %}">Add Product</a> |
        <a href="{% url 'add_category' %}">Add Category</a>
    </div>
</div>
<div class="breadcrumbs">
</div>
<div class="container">


    {% block content %}{% endblock content %}

</div>
</body>
</html>

source/my_market/templates/categories_view.html
{% extends 'base.html' %}
{% block title %}Categories{% endblock title %}
{% block content %}

<table class="table-category">
    <thead>
    <tr>
        <th scope="col" class="sortable column-category_name">
            <div class="text">
                <p>Category</p>
            </div>
        </th>
        <th scope="col" class="sortable column-actions">
            <div class="text">
                <p>actions</p>
            </div>
        </th>
    </tr>
    </thead>
    <tbody>
    {% for category in categories %}
    <tr>

        <th class="field-category_name">
            <a href="">{{ category.category_name }}</a>
        </th>
        <td class="submit-row">
            <p class="button">
                <a href="{% url 'edit_category' category.pk %}" class="button-link">Edit</a>
            </p>
        </td>
        <td class="submit-row">
            <p class="deletelink-pox">
                <a href="" class="deletelink">Delete</a>
            </p>
        </td>

    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock content %}

source/my_market/templates/detail_view_product.html
{% extends 'base.html' %}
{% block title %}Product {{ product.product_name }}{% endblock title %}
{% block content %}
<div class="content">
    <div class="cont-ditail-view-image">
        <img src="{{ product.image.url}}" alt="image" class="detail-view-image">
    </div>
    <div class="title-ditail-view">
        <h1>{{ product.product_name }}</h1>
    </div>

    <div class="category-detail-view">
        <p>{{ product.category }}</p>
    </div>
    <div class="price-detail-view">
        <p>{{ product.price }}</p>
    </div>
    <div class="description-detail-view">
        <p>{{ product.description }}</p>
    </div>
    <div class="add_date_time-detail-view">
        <p>{{ product.add_date_time }}</p>
    </div>

</div>
{% endblock content %}

source/my_market/templates/edit_category.html
<!--{% extends 'base.html' %}-->
<!--{% block title %}Edit Category{% endblock title %}-->

<!--{% block content %}-->
<!--<form method="post" id="category_form" >-->
<!--    {% csrf_token %}-->
<!--    <input type="hidden" name='id' id="id" required value=" category.id ">-->

<!--    <div>-->
<!--        <fieldset class="module aligned ">-->
<!--            <div class="form-row field-category_name">-->
<!--                <div>-->
<!--                    <label class="required" for="id_category_name">Категория:</label>-->
<!--                    <input type="text" name="category_name" value="{{ category.category_name }}" class="vTextField"-->
<!--                           maxlength="50" required id="id_category_name">-->
<!--                </div>-->
<!--            </div>-->
<!--            <div class="form-row field-description">-->
<!--                <div>-->
<!--                    <label for="id_description">Описание:</label>-->
<!--                    <input type="text" name="description" class="vTextField" value="{{category.description}}"-->
<!--                           maxlength="200" id="id_description">-->
<!--                </div>-->
<!--            </div>-->
<!--        </fieldset>-->

<!--            <input type="submit" value="Сохранить" class="default" name="_save">-->

<!--    </div>-->
<!--</form>-->
<!--{% endblock content %}-->

source/my_market/templates/index.html
{% extends 'base.html' %}
{% block content %}

{% for product in products  %}
<div class="card-main">
    <div class="cont-image-main-card">
        <img src="{{ product.image.url}}" alt="image" class="image-main-card">
    </div>
    <div class="description-card-main">
        <h2>{{product.product_name}}</h2>
        <p>{{product.category}}</p> <br>
        <h1>price: {{product.price}}$</h1>
        <br>


        <a href="{% url 'detail_view_product' product.pk %}" class="see-more">see more...</a>
    </div>


</div>
{% endfor %}
{% endblock content %}